[Discord]
token = ""                      # Your Discord app token, you get it here: https://discord.com/developers/applications/
channel = 1111111111111111111   # Channel ID of the channel that you want to mirror; the real one is the exact same length
roles = ["@everyone"]           # Roles that should be trimmed in the beginning of a message
inline_roles = ["everyone"]     # Replacement strings for roles that are pinged inside of a message
trim_roles = [true]             # Do you want to trim the above role from the beginning of a message?
linking_time = 180              # Time delay between multiple messages being linked into one post in seconds; default is 3 minutes

[RSS]
title = ""                      # The title of your feed (you can use your Discord channel name too)
description = ""                # What are you posting here / what is this channel about?
link = ""                       # The link to the RSS feed folder on your website or any other hosting solution
default = "Announcement for "   # Default title for an RSS item, in case one can't be parsed in the message (appends date afterwards)

rss_version = "2.0"             # *Version of the RSS specification, to which this dosument adheres
message_link_format = "?id="    # **A string that follows the link that is used to link to a specific item
id_xml_element = "timestamp"    # **XML element to use as the value to for item links (right now only timestamp is supported)
prefer_config = true            # *Do you prefer to use the data in the config over the existing data in the XML document?

[Local]
media_folder = "media"          # *The folder to which all downloaded files will go; used for attachements in the feed
rss_feed_file = "feed.xml"      # The file, where your RSS feed is stored

#                                 * — if you don't know what you are doing, just leave it as is, at its default value
#                                ** — depends on the implementation of your RSS frontend, or even might be unnecessary